<?php

namespace Bonder\Cli;

/**
 * Creates the bonder project and files.
 *
 * @author hbandura
 */
final class CreateCliCommand implements CliCommand {

  public function getName() {
    return "create";
  }

  public function execute(Array $options) {
    $this->create($options['--override']);
  }

  private function create($override) {
    @mkdir("bonder_app");
    @mkdir("bonder_app/config");
    if (!file_exists("bonder_app/launcher.php") || $override) {
      file_put_contents("bonder_app/launcher.php", "<?php
      // Auto generated by bin/bonder
      include __DIR__ . '/../vendor/autoload.php';
      include __DIR__ . '/session_start.php';

      \$launcher = \\Bonder\\LauncherFactory::getStandardHttp(
        include __DIR__ . '/config/resources.php',
        include __DIR__ . '/config/controllers.php',
        include __DIR__ . '/config/filters.php')->launch();
    ");
    }
    if (!file_exists("bonder_app/session_start.php") || $override) {
      file_put_contents("bonder_app/session_start.php", "<?php
    session_start();
    ");
    }
    $files = array('resources.php', 'controllers.php', 'filters.php');
    foreach ($files as $file) {
      if (!file_exists("bonder_app/config/$file") || $override) {
        file_put_contents("bonder_app/config/$file", "<?php
        return array();
      ");
      }
    }
  }
}